[package]
name = "netifs-cli"
version = "0.3.1"
authors = ["Manuel Stocker <mensi@mensi.ch>", "Daisuke Ban <exceed@alae.jp>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netifs = "0.3.1"